import numpy as np
import random
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from collections import namedtuple,deque

from buffer import Replay_Buffer
from model import QNetwork

Buffer_Size = int(1e5)  # replay buffer size
Batch_Size = 64         # minibatch size
gamma = 0.99            # discount factor
TAU = 1e-3              # for soft update of target parameters
LR = 5e-4               # learning rate 
UPDATE_EVERY = 4        # how often to update the network

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")



class Agent():
    
    
    def __init__(self, state_size, action_size, seed):
        """Initialize an Agent object.
        
        Params
        ======
            state_size (int): dimension of each state
            action_size (int): dimension of each action
            seed (int): random seed
        """
        # the state size and action size will be used to generate the Q Network
        self.state_size = state_size
        self.action_size = action_size
        ### random.seed(seed) generates sequence of random numbers by performing some operation on initial value.
        #If same initial value is used, it will generate the same sequence of random numbers
        self.seed = random.seed(seed)

        # Q-Network
        self.qnetwork_local = QNetwork(state_size, action_size, seed).to(device)
        self.qnetwork_target = QNetwork(state_size, action_size, seed).to(device)
        self.optimizer = optim.Adam(self.qnetwork_local.parameters(), lr=LR)

        # Replay memory
        self.memory = Replay_Buffer(action_size, Buffer_Size, Batch_Size, seed)
        # Initialize time step (for updating every UPDATE_EVERY steps)
        self.t_step = 0
      
    def select_act(self, state, eps=0.):
        
        " selects action based on state and epsilon"
        
        # get the state array from env, convert to tensor
        
        state = torch.from_numpy(state).float().unsqueeze(0).to(device) 
        
        # unsqueeze(0) adds a singleton dimension at 0 positon
        # useful because the states are in batches     
        # to(device) moves the tensor to the device memory, cpu or cuda
        
        ## put network in eval mode
        self.qnetwork_local.eval()
        
        #get last_layer of the network to retrive index of the max reward
        with torch.no_grad(): # torch.no_grad() prevents calculating gradients in the following block, so no backward_pass.
            action_values = self.qnetwork_local(state)
        
        self.qnetwork_local.train()
        
        if random.random() > eps:
            return np.argmax(action_values.cpu().data.numpy())
        else:
            return np.random.randint(self.action_size)        # select an action
        #random.choice(np.arange(self.action_size)) 
    
    def learn(self,experiences,gamma):
        
        states, actions, rewards, next_states, dones = experiences
        
        # Get max predicted Q values (for next states) from target model
        Q_next_states = self.qnetwork_target(next_states).detach().max(1)[0].unsqueeze(1)
        
        # detach returns a new tensor detachd from the current graph
        # final layer is (batch_size ,action_size)i.e. (64,4), max(1), will find max in the second dim(1)
        # the new tensor is (64,), we then add a singleton dimensin to it with unsqueeze
        # Q_targets_next is the max reward of the four actons for each of the 64 states
        
        Q_target = rewards + (gamma*Q_next_states*(1-dones))
        
        
        Q_expected = self.qnetwork_local(states).gather(1,actions)
        
        #gather rearranges values in the dimension (1 here) of the input tensor (64,4), 
        #as per the indices in the index tensor provided, actions here...actions carries the index of the next action taken
        # given the state in states. SO only one value will be provided..it coud be either of 0,1,2,3..based on def act and state
        #therefore output is 64,1.with reward corresponding to only that action chosen after the state.
        
        # the rewars generated by q_network local is used for comparison with Q_targets to calc.loss
        #then we update parametrs to min loss

        
        loss = F.mse_loss(Q_expected,Q_target)
        self.optimizer.zero_grad()
        loss.backward()
        self.optimizer.step()
        
        self.soft_update(self.qnetwork_local, self.qnetwork_target, TAU)
        
        
    def step(self,state,action,reward,next_state,done):
        
        self.memory.add(state,action,reward,next_state,done)
        
        self.t_step = (self.t_step+1) % UPDATE_EVERY # self.t_step will increase by 1 after every step() call
                                                    # that means every time step
        if self.t_step == 0:
            if len(self.memory) > Batch_Size:
                experiences = self.memory.sample()
                self.learn(experiences, gamma)
    
    def soft_update(self, local_model, target_model, TAU):
        """Soft update model parameters.
        θ_target = τ*θ_local + (1 - τ)*θ_target
        Params
        ======
            local_model (PyTorch model): weights will be copied from
            target_model (PyTorch model): weights will be copied to
            tau (float): interpolation parameter 
        """
        for target_param, local_param in zip(target_model.parameters(), local_model.parameters()):
            target_param.data.copy_(TAU*local_param.data + (1.0-TAU)*target_param.data)
